spring.application.name=Application

server.port=8080
server.servlet.context-path=/api

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://mysql:3306/mydatabase?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=appuser
spring.datasource.password=apppassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# Connection Pool
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

jwt.signerKey = "yzKGm9S4n5T2VC0HaJ4IGcz1LWlI90FhCWAtw3vST7Z7zoASXzMMMvnlVdTYFM8lSLyz75jjAXYfHWfzSnHcckutdyGMsxHAtt30fzk2yPiRNnDfE7B2zTfewW2Uj8hqPVRB5jXA4LXOTUx0Q71UQf0DeFHDGNnTjgeoWYnetvMYEeJAPjKBIdzTmBez2kK22BLfrKE3w4xASDfbDgRpXjFWsRKG5hp4m3ZVRTCqAzOYJbUwzHqqPzMoBGAs1rRK"